
version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://poker:pokerpass@postgres:5432/pokerdb
      - JWT_SECRET=supersecretjwt
      - SOLANA_RPC=https://api.devnet.solana.com
    depends_on:
      - redis
      - postgres
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: poker
      POSTGRES_PASSWORD: pokerpass
      POSTGRES_DB: pokerdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  pgdata:
