# render.yaml for NextLevel333/SolanaPokerBuild
# Place this file at the root of your repo (same level as server/ and client/)

databases:
  - name: poker-postgres
    engine: postgres
    plan: starter
    region: oregon

kv_stores:
  - name: poker-kv
    plan: developer
    region: oregon

jobs:
  - name: prisma-migrate
    plan: free
    type: run
    shell: bash
    env:
      - name: DATABASE_URL
      - name: REDIS_URL
      - name: JWT_SECRET
    command: |
      set -e
      cd server
      npm install
      npx prisma generate
      npx prisma migrate deploy --preview-feature

services:
  - type: web
    name: poker-server
    env: docker
    region: oregon
    plan: starter
    repo: NextLevel333/SolanaPokerBuild
    branch: main
    path: server
    buildCommand: |
      cd server
      npm ci
      npx prisma generate || true
    startCommand: |
      cd server
      npm run start
    env:
      - key: DATABASE_URL
        fromDatabase: poker-postgres
      - key: REDIS_URL
        fromKV: poker-kv
      - key: JWT_SECRET
        fromSecret: JWT_SECRET
      - key: SOLANA_RPC
        value: https://api.devnet.solana.com
      - key: ACTION_TIMEOUT_MS
        value: "20000"
      - key: SMALL_BLIND
        value: "1"
      - key: BIG_BLIND
        value: "2"

static_sites:
  - name: poker-client
    repo: NextLevel333/SolanaPokerBuild
    branch: main
    path: client
    buildCommand: |
      cd client
      npm ci
      npm run build
    publishPath: client/build
    env:
      - key: REACT_APP_SERVER
        value: https://poker-server.onrender.com
