# render.yaml for NextLevel333/SolanaPokerBuild

databases:
  - name: poker-postgres
    plan: free
    region: oregon

services:
  - type: web
    name: poker-server
    env: docker
    region: oregon
    plan: starter
    repo: https://github.com/NextLevel333/SolanaPokerBuild
    branch: main
    path: server
    buildCommand: |
      cd server
      npm ci
      npx prisma generate || true
      npm run build
    startCommand: |
      cd server
      npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: poker-postgres
          property: connectionString
      - key: REDIS_URL
        fromKV: poker-kv
      - key: JWT_SECRET
        sync: false
      - key: SOLANA_RPC
        value: https://api.devnet.solana.com
      - key: ACTION_TIMEOUT_MS
        value: "20000"
      - key: SMALL_BLIND
        value: "1"
      - key: BIG_BLIND
        value: "2"

