# render.yaml for NextLevel333/SolanaPokerBuild

databases:
  - name: poker-postgres
    plan: starter
    region: oregon

services:
  - type: web
    name: poker-server
    env: node
    region: oregon
    plan: starter
    repo: NextLevel333/SolanaPokerBuild
    branch: main
    buildCommand: |
      cd server
      npm ci
      npx prisma generate
      npx prisma migrate deploy
    startCommand: |
      cd server
      npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: poker-postgres
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: SOLANA_RPC
        value: https://api.devnet.solana.com
      - key: ACTION_TIMEOUT_MS
        value: "20000"
      - key: SMALL_BLIND
        value: "1"
      - key: BIG_BLIND
        value: "2"
